---
- name: Deploy Technitium DNS container on rseau
  hosts: rseau
  become: yes
  gather_facts: yes
  
  vars:
    dns_container_name: technitium-dns
    dns_container_ip: 10.203.1.3
    dns_data_path: /opt/technitium
    dns_admin_password: "{{ vault_dns_admin_password | default(lookup('password', '/dev/null length=20 chars=ascii_letters,digits,punctuation')) }}"
    
  tasks:
    - name: Ensure Docker is installed
      package:
        name: docker.io
        state: present
        
    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes
        
    - name: Create Technitium data directory
      file:
        path: "{{ dns_data_path }}"
        state: directory
        mode: '0755'
        
    - name: Stop existing Technitium container if running
      docker_container:
        name: "{{ dns_container_name }}"
        state: absent
      ignore_errors: yes
      
    - name: Create custom Docker network for DNS
      docker_network:
        name: dns-network
        driver: bridge
        ipam_config:
          - subnet: 10.203.1.0/24
            gateway: 10.203.1.1
            
    - name: Deploy Technitium DNS container
      docker_container:
        name: "{{ dns_container_name }}"
        image: technitium/dns-server:latest
        state: started
        restart_policy: unless-stopped
        networks:
          - name: dns-network
            ipv4_address: "{{ dns_container_ip }}"
        ports:
          - "53:5053/tcp"
          - "53:5053/udp"
          - "5380:5380/tcp"  # Web admin interface
        volumes:
          - "{{ dns_data_path }}:/etc/dns"
        env:
          DNS_SERVER_DOMAIN: doofus.co
          DNS_SERVER_ADMIN_PASSWORD: "{{ dns_admin_password }}"
          DNS_SERVER_PREFER_IPV6: "false"
          DNS_SERVER_WEB_SERVICE_HTTP_PORT: "5380"
        capabilities:
          - NET_BIND_SERVICE
        dns:
          - 1.1.1.1
          - 8.8.8.8
          
    - name: Wait for DNS service to be ready
      wait_for:
        host: "{{ dns_container_ip }}"
        port: 5380
        timeout: 60
        
    - name: Create basic DNS zone configuration script
      template:
        src: dns-zone-setup.sh.j2
        dest: /tmp/dns-zone-setup.sh
        mode: '0755'
      vars:
        dns_admin_url: "http://{{ dns_container_ip }}:5380"
        
    - name: Display DNS setup information
      debug:
        msg: |
          ✅ Technitium DNS deployed successfully!
          
          🌐 Access Points:
          - Admin Interface: http://{{ ansible_host }}:5380
          - DNS Server: {{ dns_container_ip }}:53
          
          🔧 Next Steps:
          1. Configure your router/DHCP to use {{ dns_container_ip }} as DNS
          2. Access admin interface to configure zones
          3. Add A records for homelab services
          
          📝 Default Credentials:
          - Username: admin
          - Password: {{ dns_admin_password }}
          
          🎯 Suggested DNS Records to Add:
          - gitlab.doofus.co → 10.203.3.47
          - socrates.doofus.co → 10.203.3.42
          - rawls.doofus.co → 10.203.3.47
          - rseau.doofus.co → 10.203.1.2