---
# Caddy configuration tasks

- name: Ensure Caddy configuration directory exists
  file:
    path: "{{ caddy_config_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create logs directory for Caddy
  file:
    path: "{{ caddy_config_dir }}/logs"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Validate Caddyfile syntax
  command: docker run --rm -v {{ caddy_config_dir }}:/etc/caddy:ro caddy:2-alpine caddy validate --config /etc/caddy/Caddyfile
  become_user: "{{ ansible_user }}"
  register: caddy_validation
  
- name: Display Caddyfile validation result
  debug:
    msg: "✅ Caddyfile syntax is valid"
  when: caddy_validation.rc == 0

- name: Fail if Caddyfile is invalid
  fail:
    msg: "❌ Caddyfile syntax error: {{ caddy_validation.stderr }}"
  when: caddy_validation.rc != 0