---
- name: System maintenance and updates
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      
    - name: Get list of upgradable packages
      shell: apt list --upgradable 2>/dev/null | grep -v "WARNING" | wc -l
      register: upgradable_count
      when: ansible_os_family == "Debian"
      changed_when: false
      
    - name: Display upgrade information
      debug:
        msg: "{{ (upgradable_count.stdout | int) - 1 }} packages available for upgrade"
      when: ansible_os_family == "Debian"
      
    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: upgrade_result
      when: ansible_os_family == "Debian"
      
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_os_family == "Debian"
      
    - name: Display reboot requirement
      debug:
        msg: "⚠️  SYSTEM REBOOT REQUIRED AFTER UPDATES"
      when: ansible_os_family == "Debian" and reboot_required.stat.exists
      
    - name: Clean package cache
      apt:
        autoclean: yes
        autoremove: yes
      when: ansible_os_family == "Debian"
      
    - name: Update locate database
      command: updatedb
      changed_when: false
      ignore_errors: yes
      
  handlers:
    - name: reboot system
      reboot:
        msg: "Reboot initiated by Ansible due to package updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30