---
- name: Update packages on Proxmox server
  hosts: proxmox
  gather_facts: yes
  become: yes
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      
    - name: Get list of upgradable packages
      shell: apt list --upgradable 2>/dev/null | grep -v "WARNING"
      register: upgradable_packages
      when: ansible_os_family == "Debian"
      changed_when: false
      
    - name: Display upgradable packages
      debug:
        msg: "{{ upgradable_packages.stdout_lines }}"
      when: ansible_os_family == "Debian" and upgradable_packages.stdout_lines | length > 1
      
    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: upgrade_result
      when: ansible_os_family == "Debian"
      
    - name: Display upgrade results
      debug:
        msg: |
          Packages upgraded: {{ upgrade_result.changed }}
          Upgrade output: {{ upgrade_result.stdout_lines | default([]) }}
      when: ansible_os_family == "Debian"
      
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_os_family == "Debian"
      
    - name: Display reboot requirement
      debug:
        msg: "System reboot is required after package updates"
      when: ansible_os_family == "Debian" and reboot_required.stat.exists
      
    - name: Get current kernel version
      command: uname -r
      register: current_kernel
      changed_when: false
      
    - name: Display current kernel
      debug:
        msg: "Current kernel: {{ current_kernel.stdout }}"