---
all:
  vars:
    # Global connection settings
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    tailscale_dns_servers:
      - 10.203.1.3
    
  children:
    # Proxmox infrastructure
    proxmox:
      hosts:
        socrates:
          ansible_host: 10.203.3.42
          proxmox_node_role: primary
          hardware_profile: ai_workstation
        rawls:
          ansible_host: 10.203.3.47
          proxmox_node_role: secondary  
          hardware_profile: ai_capable
        rseau:
          ansible_host: 10.203.1.2
          proxmox_node_role: tertiary
          hardware_profile: mini_pc
      vars:
        ansible_become: true
        ansible_become_method: sudo
        proxmox_cluster: homelab
        
    # Future expansion groups
    kubernetes:
      hosts:
      vars:
        container_runtime: containerd
        
    ai_workers:
      hosts:
        socrates:
      vars:
        gpu_enabled: true
        ai_frameworks:
          - pytorch
          - tensorflow
          - ollama
          
    # DNS infrastructure - DEPLOYED via Proxmox Helper Script
    dns_servers:
      hosts:
        rseau:
          ansible_host: 10.203.1.2
          dns_role: primary
          hardware_profile: mini_pc
          dns_service_ip: 10.203.1.3
          # DNS server deployed via community script
          dns_container_ip: 10.203.1.3
          dns_web_interface: "http://10.203.1.3:5380"
          dns_status: deployed
      vars:
        ansible_become: true
        ansible_become_method: sudo
        dns_server: technitium

    # Media and storage servers
    media_servers:
      hosts:
        htpc:
          ansible_host: 10.203.3.48
          hardware_profile: media_server
      vars:
        ansible_become: true
        ansible_become_method: sudo
        
    # Infrastructure as Code services
    iac_services:
      hosts:
        rawls:
          gitlab_role: primary
          services_enabled:
            - gitlab
            - caddy
            - tailscale
          future_services:
            - semaphore  # Phase 2
            - kestra     # Phase 3
      vars:
        ansible_become: true
        ansible_become_method: sudo
        iac_stack: gitlab_caddy_tailscale
        
    monitoring:
      hosts:
      vars:
        monitoring_stack: prometheus
