---
all:
  vars:
    # Global connection settings
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    
  children:
    # Proxmox infrastructure
    proxmox:
      hosts:
        socrates:
          ansible_host: 10.203.3.42
          proxmox_node_role: primary
          hardware_profile: ai_workstation
      vars:
        ansible_become: true
        ansible_become_method: sudo
        proxmox_cluster: homelab
        
    # Future expansion groups
    kubernetes:
      hosts:
      vars:
        container_runtime: containerd
        
    ai_workers:
      hosts:
        socrates:
      vars:
        gpu_enabled: true
        ai_frameworks:
          - pytorch
          - tensorflow
          - ollama
          
    monitoring:
      hosts:
      vars:
        monitoring_stack: prometheus