---
galaxy_info:
  author: Kellen
  description: Common system configuration and packages
  company: Homelab
  license: MIT
  min_ansible_version: 2.14
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - system
    - common
    - packages
    - security

dependencies: []